;**
;**	Logics for room 260 -- On the Beach
;**
;**	LSL3:  Passionate Patti in Pursuit of the Pulsating Pectorals
;**	       Copyright 1989
;**		by Al Lowe, Bill Skirvin, Carlos Escobar, and Roger Hardy
;**
;**	Last Update:	June 16, 1989
;**


(define	vLizard						260)
	(define	lLizRisingEast		2)
	(define	lLizRisingWest		3)
	(define	lLizTongueEast		4)
	(define	lLizTongueWest		5)


(enum												;**	LizardScript state values
	LizIntro
	bringLizIn
	pauseB4standing
	standLizUp
	LizStanding
	LizLicking
	makeLizGoDown
	byeByeLiz
	emergencyExit
	hereComesLizardDick
	LizHalfOut
	lickDick
)


(enum												;**	RoomScript state values
	intro
	drowning
	deathOccurredSuddenly
	UBdying
	gotoTtowel
	bendOverTtowel
	takeTtowel
	TtowelDone
	gotoLtowel
	spreadTtowel
	getOnTowel
	undressLarry
	lieDown
	onLtowel
	startRoasting
	roasting
	cooked
	wellDone
	getUp
	getDressed
	gotoTheTowel
	bendOverLtowel
	gotLtowel
	LtowelDone
	getLaid
	hugAlittle
	rollAbout
	knifeManReady
	riseToTheOccasion
	bargain
	thatWasRude
	sheffieldSteel
	comeInAcase
	twentyBucksBitch
	givesMoney
	TgoesDownAgain
	youContemplate
	screwSomeMore
	rollAgain
	larryGetsCrabs
	CRABS
	jumpingAround
	jumpingDone
	RweThru
	roNesponse
)

