;**
;**	Header for rooms 430 & 431 -- Showroom stage
;**
;**	LSL3:  Passionate Patti in Pursuit of the Pulsating Pectorals
;**	       Copyright 1989
;**		by Al Lowe, Bill Skirvin, Carlos Escobar, and Roger Hardy
;**
;**	Last Update:	September 30, 1989
;**


(define	vRoom							430)
	(define	lCurtain				0)
	(define	lBigLight			1)
	(define	lBigLightOnFloor	2)
	(define	lTrapdoor			3)
	(define	lHoist				4)
	(define	lSpotlights			5)			;**	Lights & cels are numbered
	(define	lFloorlight			6)			;**	same as visual screen colors.
	(define	lMoney		  		7)
	(define	lVeggies				8)
	(define	lTomatoes			9)

(define	vLroom						431)	;**	Larry's loops are numbered
													;**	same as visual screen colors.
(define	vCherriDancingSmall		432)
	(define	lStartSpin			0)
	(define	lSpin 				1)
	(define	lEndSpin				2)
	(define	lKick		 			3)
	(define	lKickHigh 			4)

(define	vDancers						433)

;(define	vCherriFace					435)	;**	unused in this room
;(define	vCherri						436)
(define	vLdeadEmbarrassment		437)	;**	in case of death
;(define	vLziegfield					708)


;(define	sTimpaniRoll				010)
;(define	sApplause					013)
(define	sShowroomDancing			430)
;(define	sCherriDancing				431)
(define	sLarryDancing				432)
(define	sBoosWhistlesCatcalls	433)

(define	spotlightY					 52)
(define	floorlightY  				 97)
(define	runwayY						 95)
(define	cherriUpY	 				 86)
(define	cherriDownY					140)
(define	hoistUpY						109)
(define	hoistDownY					163)


