;**
;**	menu.sh -- header used by 000, 010, and 020 for menus
;**
;**	LSL3:  Passionate Patti in Pursuit of the Pulsating Pectorals
;**	       Copyright 1989
;**		by Al Lowe, Bill Skirvin, Carlos Escobar, and Roger Hardy
;**
;**	Last Update:	September 20, 1989
;**


(enum
	$100 sierraM
	aboutI
	helpI

	$200 fileM
	saveI
	restoreI
	autosaveI
	divider201I
	restartI
	quitI

	$300 actionM
	pauseI
	invI
	repeatI
	divider301I
	colorsI
	divider302I
	bossI					;**	filthI
	expletiveI

	$400 speedM
	speedI
	divider401I
	fasterI
	normalI
	slowerI
	divider402I
	textSpeedI

	$500 soundM
	volumeI
	soundI

	$600	cheatM
	roomI
	noteI
	rgTimeI
	inputI
	divider601I
	visualI
	priorityI
	controlI
	divider602I
	tglDebugI
	memI
	quickQuitI

	$700	debugM
	debugHelpI
	gameI
	clothingI
	sexI
	egoI
	gridI
	writeEgoI
)

