;**
;**	scene.sh -- quick 1-line description of each scene
;**
;**	LSL3:  Passionate Patti in Pursuit of the Pulsating Pectorals
;**	       Copyright 1989
;**		by Al Lowe, Bill Skirvin, Carlos Escobar, and Roger Hardy
;**
;**	Last Update:	October 18, 1989
;**


000 -- real programmers still call it "Zero"
010 -- Menu (outputs to script.997; not 10 as you would suppose)
020 -- Debug menu
021 -- ShowState procedure (only)
022 -- QA helper
030 -- Inventory text wrangler
040 -- Dying script
041 -- Falling region
042 -- Lei script
043 -- Carving script
044 -- Weaving script
045 -- Locker combination script
046 -- Locker combination text
050 -- DOOR
051 -- AUTODOOR
070 -- girl close up locale
071 -- big face close up region
080 -- generic male clerk locale, if Larry
081 -- generic male clerk locale, if Patti
090 -- Boss Key

120 -- Title Screen
130 -- Opening Cartoon
140 -- Copy protection check room
141-? -- Trivia questions

200 -- Vista Point
203 -- Larry the Hero plaque
206 -- Peep show
210 -- Path with granadilla
213 -- Park bench
216 -- L & K's home
220 -- Outside Fat City
230 -- Outside Chip & Dale's
235 -- Orchid deadend
240 -- Outside Comedy Club
245 -- Bamboo maze entrance
250 -- Outside the Casino
253 -- Restroom
260 -- On the Beach
265 -- Tawni face
266 -- Tawni full length shot
290 -- Speed test room
299 -- Village	locale

300 -- Fat City exterior
305 -- Natives, Inc. exterior
310 -- Dewey, Cheatum & Howe exterior
320 -- Dewey, Cheatum & Howe
323 -- Suzi's Office
324 -- Suzi's Office Party!
325 -- Suzi close up
330 -- Chip & Dale's
335 -- Dale close up
340 -- Comedy Club
350 -- Native's Inc.
355 -- Ken's Office
360 -- "Fat City"
365 -- Tanning Booth
366 -- Tanning Booth lit up
370 -- Locker Room
375 -- Shower
380 -- Weight Room
390 -- Aerobics studio
395 -- Bambi close up
399 -- Fat City locale

400 -- Casino Entrance
410 -- Casino
415 -- Mirrored hallway, West
416 -- Mirrored hallway, East
417 -- Hallway messages (for 415/416)
420 -- Maitre D'
421 -- Stage Manager's script for 420
422 -- Cherri's script for 420
430 -- Showroom, Cherri dancing
431 -- Showroom,  Larry dancing
435 -- Cherri close up
440 -- Back Stage
450 -- Piano Bar
455 -- Patti close up
460 -- Hotel Desk
470 -- Elevator
480 -- Patti's Penthouse (if Larry)
481-484 -- Patti's Penthouse & Doing It With Larry
499 -- Casino locale

500 -- Bamboo Maze (uses 501-504 for overlayPics on pic.500 and 506-509 for pic.505)
510 -- Stream before waterfall
520 -- Cliff West
523 -- Cliff East
525 -- Rappelling
530 -- Marijuana Ledge
535 -- On the Rope
540 -- Feral Pig
550 -- Beside the River
560 -- Whitewater Log Ride
580 -- Captured!
585 -- Cannibal Village
590 -- Larry Stew
599 -- Jungle locale

600 -- Falling thru Space (uses pic.099)
610 -- PQ1 Map
620 -- Prop room
630 -- SQ2 Opening scene
640 -- KQ4 Tongue
650 -- L&P on Deck
699 -- Sierra locale

