ncopy C:\system\sci.exe g:\games\%game%\script
ncopy C:\system\scri*.* g:\games\%game%\script
ncopy C:\system\voca*.* g:\games\%game%\script
ncopy C:\system\text*.* g:\games\%game%\script

ncopy *.*               g:\games\%game%\sci
ncopy script            g:\games\%game%\script
ncopy pic               g:\games\%game%\pic
ncopy view              g:\games\%game%\view
ncopy sound             g:\games\%game%\sound
