L:
cd \games\%game%
C:
cd \%game%			
upd             from L:           %1
upd qa          from L:qa         %1
upd script      from L:script     %1
upd pic         from L:pic        %1
upd view        from L:view       %1
upd sound       from L:sound      %1
upd vols        from L:vols       %1
upd vols\360    from L:vols\360   %1
upd vols\720    from L:vols\720   %1
upd \system     from L:system     %1
upd \system\exe from L:system\exe %1
C:
