C:
cd \%game%
L:
cd \games\%game%
upd            from c:\%game%          %1
upd qa         from c:\%game%\qa       %1
upd script     from c:\%game%\script   %1
upd pic        from c:\%game%\pic      %1
upd view       from c:\%game%\view     %1
upd sound      from c:\%game%\sound    %1
upd vols       from c:\%game%\vols     %1
upd play       from c:\%game%\vols\360\resource.* %1
upd system     from c:\system          %1
upd system\exe from c:\system\exe      %1
L:
